version: '3.4'

services:
  basket.api:
    image: ${DOCKER_REGISTRY-}basketapi
    build:
      context: .
      dockerfile: Basket.Api/Dockerfile

  catalog.api:
    image: ${DOCKER_REGISTRY-}catalogapi
    build:
      context: .
      dockerfile: Catalog.Api/Dockerfile

  basket.db:
    image: redis:alpine
    ports:
      - "6379:6379"

  catalog.db:
    image: mongo:latest
    
volumes:
  mongo_data:
    driver: local  